---
title: "Apprentissage Statistique"
subtitle: "New York city Airbnb"
author: "Duong Nguyen & Julien Le Mauff"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document: default
---

```{r setup, include=F, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cache=TRUE,include=F,message=FALSE, warning=FALSE}
library(caret)
library(dplyr)
library(psych)
library(caret)
library(ggplot2)
library(ggmap)
```

```{r cache=TRUE,include=F,message=FALSE, warning=FALSE}
data <- read.csv("/Users/ngyduong/Documents/Machine Learning/Github_projects/NewYork_Airbnb/NYC_Airbnb/Data/data.csv", sep = ",")
```

<!-- DATA EXPLORATION --> 

```{r cache=TRUE,include=F,message=FALSE, warning=FALSE}
summary(data[,-c(1:4,13)]) 
# sans les ID, hostID, nom propre des hôtes et dates

# NA ?
na_count <- data %>% summarise_each(funs(sum(is.na(.))))
# reviews_per_month : 10052 NA (près de 21% de valeur manquante)

# \!/ Si number_of_reviews == 0 alors reviews_per_month == 0
# \!/ Si number_of_reviews == 0 il n'y a pas non plus de "last_review"

data <- mutate(data, reviews_per_month = ifelse(number_of_reviews==0, 
                                                as.integer(0),
                                                reviews_per_month))
```

```{r cache=TRUE,include=T,message=FALSE, warning=FALSE}
# Plot histogramme (density)
features_discrete <- names(select_if(data[,-c(1:4)],is.factor))
for (i in features_discrete) { 
  plot(data[i],
       main = i,
       col = "deepskyblue")
}
```

```{r cache=TRUE,include=T,message=FALSE, warning=FALSE}
features_numeric <- names(select_if(data[,-c(1:4,7:8)],is.numeric))

par(mfrow=c(1,2))
for (i in features_numeric){
  hist(log(data[,i]), main = paste("log of", i), xlab="",
       col = "deepskyblue", probability = T)
  lines(density(log(data[,i])), lwd = 2, col = "dodgerblue4")
  hist(data$i, main = i, xlab="", col = "darkseagreen1", 
       probability = T)
  lines(density(data$i), lwd = 2, col = "forestgreen")
}

# Log price et reviews_per_month (?)
```

<!-- GRAPHICAL ANALYSIS (INDEX) --> 

```{r cache=TRUE,include=T,message=FALSE, warning=FALSE}

# Log price of New York city airbnb by neighborhood groups

theme <- theme(plot.title = element_text(hjust = 0.5), 
               plot.background = element_rect(fill = "#BFD5E3"))

ggplot(data, mapping = aes(x = neighbourhood_group, y = log(price))) +
  geom_boxplot(outlier.colour = "darkblue", outlier.size = 0.5,
               color="deepskyblue", fill="cyan", alpha=0.2) + 
  ggtitle("New York airbnb by neighborhood groups") +
  labs(x = "Neighbourhood groups", y = "Log of Price (in USD)") + 
  theme

# Log price of New York city airbnb by room types and neighborhood groups

ggplot(data, mapping = aes(x = neighbourhood_group, y = log(price), 
                           fill = room_type)) +
  geom_boxplot(outlier.colour = "darkblue", outlier.size = 0.5) + 
  ggtitle("New York airbnb by room types and neighborhood groups") +
  scale_fill_discrete(name = "Room types") +
  labs(x = "Neighbourhood groups", y = "Log of Price (in USD)") +
  theme

# Relation between Price (in log) and minimum numbers of nights

ggplot(data, mapping = aes(x = minimum_nights, y=log(price))) +
  geom_point(size = 0.5, alpha = 0.2, color = "darkblue") +
  ggtitle("Relation between Price (in log) and minimum numbers of nights") +
  labs(x = "Minimum number of nights", y = "Log of Price (in USD)") + theme

# Relation between Price (in log) and the amount of listing per host

ggplot(data, mapping = aes(x = calculated_host_listings_count, y=log(price))) +
  geom_point(size = 0.5, alpha = 0.2, color = "darkblue") +
  ggtitle("Relation between Price (in log) and the amount of listing per host") +
  labs(x = "Amount of listing per host", y = "Log of Price (in USD)") + theme

# Relation between Price (in log) and the number of reviews per month

ggplot(data, mapping = aes(x = log(reviews_per_month), y=log(price))) +
  geom_point(size = 0.5, alpha = 0.2, color = "darkblue") +
  ggtitle("Relation between Price (in log) and \n the number of reviews per month (in log)") +
  labs(x = "Number of reviews per month (in log)", y = "Price (in log)") + theme
```

<!-- SPATIAL HEATMAP --> 

```{r cache=TRUE,include=T,message=FALSE, warning=FALSE}

by_neighbourhood <- group_by(data, neighbourhood) %>% 
  summarise(longitude = median(longitude), 
            latitude = median(latitude), 
            prix_moyen = mean(price),
            nb_nuit_minimum_moyen = mean(minimum_nights),
            nb_review_moyen = mean(number_of_reviews),
            availability_moyen = mean(availability_365))

for (i in by_neighbourhood$neighbourhood) {
  for (j in data$neighbourhood) {
    if (i == j) {
      a = unique(as.character(data[data$neighbourhood==j,"neighbourhood_group"]))
      by_neighbourhood[by_neighbourhood$neighbourhood==i,"Arrondissements"]<-a
      }
    }
}

by_neighbourhood$Arrondissements <- as.factor(by_neighbourhood$Arrondissements)

height <- max(data$latitude) - min(data$latitude)
width <- max(data$longitude) - min(data$longitude)
borders <- c(bottom  = min(data$latitude)  - 0.1 * height,
             top     = max(data$latitude)  + 0.1 * height,
             left    = min(data$longitude) - 0.1 * width,
             right   = max(data$longitude) + 0.1 * width)

map <- get_stamenmap(borders, zoom = 11, maptype = "terrain")

## prix moyen par quartiers et arrondissement

ggmap(map) +
  geom_point(by_neighbourhood, 
             mapping = aes(x = longitude, y = latitude, 
                           col = prix_moyen,
                           shape = Arrondissements)) +
  scale_colour_gradient(low = "blue", high = "red") + theme +
  labs(x = "", y = "") + 
  ggtitle("New York city airbnb mean price heatmap") 

## availability_moyen par quartiers et arrondissement

ggmap(map) +
  geom_point(by_neighbourhood,
             mapping = aes(x = longitude, y = latitude,
                           col = availability_moyen,
                           shape = Arrondissements)) +
  scale_colour_gradient(low = "blue", high = "red") + theme +
  labs(x = "", y = "") +
  ggtitle("New York city airbnb availability_moyen heatmap")
```

```{r cache=TRUE,include=T,message=FALSE, warning=FALSE}
cross <- group_by(data, neighbourhood_group) %>% 
  summarise(longitude = median(longitude), 
            latitude = median(latitude), 
            availability_moyen = mean(availability_365),
            availability_median = median(availability_365),
            prix_moyen = mean(price),
            prix_median = median(price))

ggmap(map) +
  geom_point(cross,
             mapping = aes(x = longitude, y = latitude,
                           col = prix_moyen,
                           size = availability_moyen,
                           shape=neighbourhood_group)) +
  scale_colour_gradient(low = "blue", high = "red") + theme +
  labs(x = "", y = "") 
```